coverage:
  precision: 2
  round: down
  range: 50...100

  notify:
    slack:
      default:
        url: secret:sHR8A1QwZQ51fJEmJkZ+LEuGq3fnwXosld1bsMl63+k9RGtM1yQF5PwT0hR99DauM8aFHIyKXLFJ/6m+16h0ZAcTSIidcuxIuIc2Dtc5sb5yuAkk4MG8QRzpMsmqayUfOveg86353ZSCJ5i/m91r0XW3JQB1QcwHcDO+q2QBwog=
        branches: null
        threshold: null
        attachments: "sunburst, diff"